### ISSUE TITLE
Release description

### ISSUE THREAD

**Issue by szepeviktor** [ergebnis/php-cs-fixer-config-template#238]
What generates e.g. this release body? https://github.com/ergebnis/php-cs-fixer-config/releases/tag/2.5.3
I couldn't find it in the action: https://github.com/actions/create-release/blob/main/src/create-release.js
nor in the workflow file https://github.com/ergebnis/php-cs-fixer-config/blob/2.5.3/.github/workflows/release.yaml

Thank you!

**Comment by localheinz** [comment]
Ha, sorry for the delay, @szepeviktor!

I should use [`ergebnis/github-changelog`](https://github.com/ergebnis/github-changelog), but since I have fiddled around with it and not found the time to fix some issues there, I currently use [`localheinz/github-changelog:0.6.0`](https://github.com/ergebnis/github-changelog/releases/tag/0.6.0)!

Here is what I typically do:

```
$ composer global require localheinz/github-changelog:0.6.0
```

then I list the tags for the repository I want to create release notes for:

```
$ git tag
```

followed by

```
$ github-changelog generate --auth-token=<auth-token> <tag>
```

Hope it helps!

**Comment by szepeviktor** [comment]
Thank you.
